const sidebars = {
  wikiSidebar: [
    {
      type: 'link',
      label: '🏠 Home',
      href: '/',
    },
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;